/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "check.h"
#include "token.h"

extern UsersIdDB usersIdDatabase;

char **
request_authorization_func_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	result = calloc(ERROR_LENGTH,sizeof(char));

    // Check if argp is in the database
    for (unsigned int i = 0; i < usersIdDatabase.number_of_users; ++i) {
        if (strcmp(argp[0], usersIdDatabase.users[i]) == 0) {
            // User found in the database, generate and return an access token
            char *token = generate_access_token(argp[0]);
            strcpy(result, token);
            free(token); // Remember to free the allocated token after use
			printf("%s\n",result);
            return &result;
        }
    }

    // User not found in the database
    strcpy(result, "USER_NOT_FOUND");
	printf("USER_NOT_FOUND\n");
    return &result;
}

struct request_access_token *
request_access_token_func_1_svc(struct request_authorization *argp, struct svc_req *rqstp)
{
	static struct request_access_token  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
validate_delegated_action_func_1_svc(struct validate_delegated_action *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
approve_request_token_func_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
